# Generated by Django 4.1 on 2024-04-24 23:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sender',
            new_name='ReceiverOfReview',
        ),
        migrations.RenameModel(
            old_name='Receiver',
            new_name='SenderOfReview',
        ),
        migrations.RenameField(
            model_name='receiverofreview',
            old_name='sender',
            new_name='reciever',
        ),
        migrations.RenameField(
            model_name='senderofreview',
            old_name='reciever',
            new_name='sender',
        ),
    ]
