# Generated by Django 4.1 on 2024-04-24 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_catalog', '0002_rename_sender_receiverofreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport_catalog.receiverofreview'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport_catalog.senderofreview'),
        ),
    ]
