# Generated by Django 4.1 on 2024-04-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_catalog', '0005_alter_review_reciever'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiverOfReview',
        ),
    ]
