# Generated by Django 4.1 on 2024-04-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_catalog', '0007_alter_review_reciever_alter_review_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='spotsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport_catalog.sportuser'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcv', to='sport_catalog.sportuser'),
        ),
        migrations.AlterField(
            model_name='review',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snd', to='sport_catalog.sportuser'),
        ),
    ]
