# Generated by Django 4.1 on 2024-04-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_catalog', '0008_alter_application_spotsman_alter_review_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport_catalog.sportuser'),
        ),
        migrations.AlterField(
            model_name='userssporttypes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport_catalog.sportuser'),
        ),
    ]
