# Generated by Django 4.1 on 2024-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_catalog', '0009_alter_complaint_moderator_alter_userssporttypes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportuser',
            name='isManager',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportuser',
            name='isSportsMen',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
